"""fix_data_integrity_datetime_date_age_fk

Revision ID: b5add256af78
Revises: 
Create Date: 2026-04-10 10:09:48.034112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b5add256af78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_act_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_act_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['medical_act_id'], ['medical_acts.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_act_staff_id'), 'medical_act_staff', ['id'], unique=False)
    op.alter_column('act_documents', 'act_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # Add datetime_scheduled with default, then drop old columns
    op.add_column('appointments', sa.Column('datetime_scheduled', sa.DateTime(), server_default=sa.func.now(), nullable=True))
    op.alter_column('appointments', 'patient_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('appointments', 'time')
    op.drop_column('appointments', 'date')
    # Now populate datetime_scheduled if empty and make it NOT NULL
    op.execute("UPDATE appointments SET datetime_scheduled = NOW() WHERE datetime_scheduled IS NULL")
    op.alter_column('appointments', 'datetime_scheduled', existing_type=sa.DateTime(), nullable=False)
    op.alter_column('medical_acts', 'patient_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('medical_acts', 'date',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Date(),
               nullable=False)
    op.create_foreign_key(None, 'medical_acts', 'users', ['doctor_id'], ['id'])
    op.drop_column('medical_acts', 'assigned_staff_ids')
    op.alter_column('patients', 'date_of_birth',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_column('patients', 'age')
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('patients', sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('patients', 'date_of_birth',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.add_column('medical_acts', sa.Column('assigned_staff_ids', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'medical_acts', type_='foreignkey')
    op.alter_column('medical_acts', 'date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('medical_acts', 'patient_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('appointments', sa.Column('date', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('appointments', sa.Column('time', mysql.VARCHAR(length=10), nullable=True))
    op.alter_column('appointments', 'patient_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('appointments', 'datetime_scheduled')
    op.alter_column('act_documents', 'act_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_medical_act_staff_id'), table_name='medical_act_staff')
    op.drop_table('medical_act_staff')
    # ### end Alembic commands ###
